Assignment2/Models/ErrorViewModel.cs
using System;

namespace Assignment2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment2/Models/TwitterPost.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace Assignment2.Models
{
    public class TwitterPost
    {
        public string tweet { get; set; }

        public dynamic file { get; set; }

    }
}

Assignment2/Controllers/RedditController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RedditImplementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using R = RedditImplementation;

namespace Assignment2.Controllers
{
    public class RedditController : Controller
    {

        // GET: RedditController
        public async Task<IActionResult> Index()
        {
            R.Reddit objReddit = new R.Reddit();
            var lstPost = await objReddit.GetDBPost();
            return View(lstPost.OrderByDescending(x => x.Created));
        }

        public async Task<IActionResult> GetMyPosts()
        {
            R.Reddit objReddit = new R.Reddit();
            var lstPost = await objReddit.GetMyPosts();
            if (lstPost.Any())
            {
                await objReddit.SaveData(lstPost);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("Reddit/GetTaggedPost/{hashTag?}")]
        public async Task<IActionResult> GetTaggedPost(string hashTag)
        {
            hashTag ??= "AskReddit";
            R.Reddit objReddit = new R.Reddit();
            var lstPost = await objReddit.GetHashTag(hashTag);
            if (lstPost.Any())
            {
                await objReddit.SaveData(lstPost);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Truncate()
        {
            R.Reddit objReddit = new R.Reddit();
            var msg = await objReddit.DeleteAll();
            if (string.Compare(msg, "DeleteAll", true) == 0)
                ViewBag.Message = "Deleted Successfully";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(string text, IFormFile file)
        {
            R.Reddit objTwitter = new R.Reddit();
            if (file != null)
                await objTwitter.MakePost(text, file);
            else if (!string.IsNullOrWhiteSpace(text))
                await objTwitter.MakePost(text);
            return RedirectToAction("Index");
        }

        public ActionResult GetToken(string state, string code)
        {
            RedditUtil.code = code;
            RedditUtil.state = state;
            return View();
        }

        public IActionResult OpenModelPopup()
        {
            return View();
        }
    }
}

Assignment2/Controllers/TwitterController.cs
using Assignment2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TwitterImplementation;

namespace Assignment2.Controllers
{
    public class TwitterController : Controller
    {
        private readonly ILogger<TwitterController> _logger;

        public TwitterController(ILogger<TwitterController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> IndexAsync()
        {
            try
            {
                Twitter tweet = new Twitter();
                var res = await tweet.GetDBTweets();
                return View(res.OrderByDescending(x => x.CreatedAt));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message + " : " + ex.StackTrace;
                return View(new List<Tweet>());
            }
        }

        public async Task<IActionResult> GetMyTweet()
        {
            Twitter objTwitter = new Twitter();
            var res = await objTwitter.GetUserTweets();
            var msg2 = objTwitter.SaveData(res);
            if (string.Compare(msg2.Result, "SaveData", true) == 0)
                ViewBag.Message = "DB updated successfully";

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetMyTimeline()
        {
            Twitter objTwitter = new Twitter();
            var res = await objTwitter.GetUserHomeTweets();
            var msg2 = objTwitter.SaveData(res);
            if (string.Compare(msg2.Result, "SaveData", true) == 0)
                ViewBag.Message = "DB updated successfully";

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Truncate()
        {
            Twitter objTwitter = new Twitter();
            var msg = objTwitter.DeleteAll();
            if (string.Compare(msg.Result, "DeleteAll", true) == 0)
                ViewBag.Message = "Deleted Successfully";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> MakeTweet(string tweet, IFormFile file)
        {
            Twitter objTwitter = new Twitter();
            if (file != null)
                await objTwitter.MakeTweet(tweet, file);
            else if (!string.IsNullOrWhiteSpace(tweet))
                await objTwitter.MakeTweet(tweet);
            return RedirectToAction("Index");
        }

        public IActionResult OpenModelPopup()
        {
            return View("TweetPopUp");
        }
    }
}

Assignment2/Views/Reddit/GetToken.cshtml
@{
    ViewData["Title"] = "Get Token";
}
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            window.close();
        });
    </script>

    <body>
        <script type="text/javascript">
            debugger;
            window.close();
        </script>
    </body>
</body>

Assignment2/Views/Reddit/Index.cshtml
@model IEnumerable<RedditImplementation.RedditPost>

@{
    ViewData["Title"] = "Reddit";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<h3>Reddit Posts</h3>

<p>
    @*<a asp-action="Create">Create New</a>*@
    <table cellspacing="10" , cellpadding="10">
        <tr>
            <td>
                <a asp-action="Truncate">Truncate Data</a><br />
            </td>
            <td>
                <a asp-action="GetMyPosts">Get MyPosts</a><br />
            </td>
            <td>
                @using (Html.BeginForm("GetTaggedPost", "Reddit", FormMethod.Post))
                {
                    <input type="text" value="Jalpa96164182" name="hashTag" /> <button type="submit">Get SubReddit</button><br />
                }
            </td>
            <td>
                <button type="button" class="btn-block" data-toggle="modal" id="ClickMe" data-target="#myModal" style="background-color: tomato; font-family:Verdana; color: white;" name="ClickMe">Create Post</button>
            </td>
    </table>
</p>
<div class="modal fade" id="myModal" role="dialog" data-url='@Url.Action("OpenModelPopup","Reddit")'></div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.btn-block').click(function () {
            var url = $('#myModal').data('url');
            $.get(url, function (data) {
                $("#myModal").html(data);
                $("#myModal").modal('show');
            });
        });
    });
</script>


<table class="table">
    <thead>
        <tr>
            <th>
                Subreddit
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                Up Votes
            </th>
            <th>
                Upvote Ratio
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                Created Time
            </th>
            <th>
                Down Votes
            </th>
            <th>
                Edited Time
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fullname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Permalink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SelfText)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SelfTextHTML)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subreddit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpVotes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpvoteRatio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DownVotes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Edited)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fullname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Permalink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SelfText)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SelfTextHTML)
                </td>
            </tr>
        }
    </tbody>
</table>

Assignment2/Views/Reddit/OpenModelPopup.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div class="PlaceHolder"></div>
@using (Html.BeginForm("CreatePost", "Reddit", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="myModal-lable">Create Post</h6>
                <button type="button" id="btnClose" class="btnClose close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form asp-action="CreatePost" enctype="application/x-www-form-urlencoded">
                    <div class="form-group">
                        <textarea id="txtArea" class="form-control" maxlength="500" cols="60" rows="8" name="text">
                        </textarea>
                        @*<input type="file" id="fileUpload" accept="audio/*,video/*,image/*" name="file"/>*@
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="btnOk">Post</button>
                <button type="button" id="btnClose" class="btnClose btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
     $(document).ready(function () {
         $('.btnClose').click(function () {
             location.reload();
         });
     });
</script>

Assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">*@
    <style type="text/css">
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Twitter" asp-action="Index">Assignment2</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Twitter" asp-action="Index">Twitter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reddit" asp-action="Index">Reddit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Assignment2 - <a asp-area="" asp-controller="Twitter" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Assignment2/Views/Twitter/Index.cshtml
@model IEnumerable<TwitterImplementation.Tweet>

@{
    ViewData["Title"] = "Twitter";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<h3>Twitter Posts</h3>

<p>
    <table cellspacing="10" , cellpadding="10">
        <tr>
            <td>
                <a asp-action="Truncate">Truncate Data</a><br />
            </td>
            <td>
                <a asp-action="GetMyTweet">Get My Tweets</a><br />
            </td>
            <td>
                <a asp-action="GetMyTimeline">Get My Timeline</a><br />
            </td>
            <td>
                <button type="button" class="btn-block" data-toggle="modal" id="ClickMe" data-target="#myModal" style="background-color:#1DA1F2; font-family: system-ui, -apple-system, BlinkMacSystemFont, Roboto, Ubuntu, , sans-serif; color:white;" name="ClickMe">Tweet it</button>
            </td>
    </table>
    @*<a asp-action="MakeTweet">Tweet Now  !!!</a><br />*@    
</p>
<div class="modal fade" id="myModal" role="dialog" data-url='@Url.Action("OpenModelPopup","Twitter")'></div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.btn-block').click(function () {
            var url = $('#myModal').data('url');
            $.get(url, function (data) {
                $("#myModal").html(data);
                $("#myModal").modal('show');
            });
        });
    });
</script>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    Tweet Url
                </th>
                <th>
                    Tweet
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Language)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MediaCount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RetweetCount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReplyCount)
                </th>
                <th>
                    CreatedBy
                </th>
                <th>
                    Created Time
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TweetUrl)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullText)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Language)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MediaCount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RetweetCount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReplyCount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedByName) (@@@Html.DisplayFor(modelItem => item.CreatedByUsername))
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedAt)
                    </td>
                    @*<td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>*@
                </tr>
            }
        </tbody>
        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
            </script>

        }
    </table>

Assignment2/Views/Twitter/TweetPopUp.cshtml
@model TwitterPost

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div class="PlaceHolder"></div>
@using (Html.BeginForm("MakeTweet", "Twitter", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="myModal-lable">Make a Tweet</h6>
                <button type="button" id="btnClose" class="btnClose close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form asp-action="MakeTweet" enctype="application/x-www-form-urlencoded">
                    <div class="form-group">
                        <textarea id="txtArea" class="form-control" maxlength="500" cols="60" rows="8" asp-for="tweet">
                    </textarea>
                    <input type="file" id="fileUpload" accept="audio/*,video/*,image/*" asp-for="file" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="btnOk">Post</button>
                <button type="button" id="btnClose" class="btnClose btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $('.btnClose').click(function () {
            location.reload();
        });
    });

        @*$('#btnOk').click(function () {
            var form = $(this).parent().parent().children('.modal-body').find('form');
            var actionUrl = form.attr('action');
            var data = form.serialize();
            debugger;
            var text = $("#txtArea").val();
            var files = $("#fileUpload").get(0).files;

            if (files.length > 0) {
                data2.append("file", files[0]);
            }
            data2.append("tweet", text);

            $.post(actionUrl, data2).done(function () {
                window.alert("Tweet Posted");
                 var url = '@Url.Action("Index", "Twitter")';
                 window.location.href = url;
            });
        });
    });*@


</script>